AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

MethodLength:
  Max: 35

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']