AllCops:
  TargetRubyVersion: 2.6.3
  DisabledByDefault: true
  Include:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/inputs/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/policies/**/*'
    - 'app/services/**/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    - 'db/schema.rb'
    - 'spec/fixtures/**/*'
    - 'bin/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

MethodLength:
  Max: 35

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']

Metrics/AbcSize:
  Max: 40
